name: CI

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2.2']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with: 
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically        
    - name: Set up yarn
      uses:  actions/setup-node@v3
      with: 
        node-version: '18.x'
    - run: yarn
    - run: bundle exec rake assets:precompile
    - run: bundle exec rake test


  # deploy:
  #   name: Capistrano Deploy to Server
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Install SSH key to Server
  #       uses: shimataro/ssh-key-action@v2
  #       with:
  #         key: ${{ secrets.SSH_KEY }}
  #         name: github-actions
  #         known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'
  #         config: |
  #           host lsscse.com
  #             IdentityFile ~/.ssh/github-actions
  #             IdentitiesOnly yes
  #             ForwardAgent yes

  #     - name: Adding Known Hosts
  #       run: ssh-keyscan -H ${{ secrets.SSH_HOST }}

  #     - uses: actions/checkout@v2
  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: ['3.2.2']
  #         bundler-cache: true # runs 'bundle install' and caches installed gems automatically

  #     - name: Deploy to production
  #       run: |
  #         eval "$(ssh-agent -s)"
  #         ssh-add ~/.ssh/github-actions
  #         bundle exec cap production deploy

  # deploy:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       ruby-version: ['3.2.2']
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: ${{ matrix.ruby-version }}
  #         bundler-cache: true
  #     - uses: webfactory/ssh-agent@v0.8.0
  #       with:
  #         ssh-private-key: ${{ secrets.TOMO_DEPLOY_PRIVATE_KEY }}

  
      # - run: bundle exec cap deploy -s git_ref=$GITHUB_SHA
      # - run: bundle exec cap production deploy #git_ref=$GITHUB_SHA

# name: Deploy To Server

# on:
#   # Deploy on merge to main
#   push:
#     branches: [ main ]
# #  # Manually deploy branch
# #  workflow_dispatch:
# #    branches: [ main ]

# jobs:
#   deploy:
#     name: Capistrano Deploy to Server
#     runs-on: ubuntu-latest

#     steps:
#       - name: Install SSH key to Server
#         uses: shimataro/ssh-key-action@v2
#         with:
#           key: ${{ secrets.SSH_KEY }}
#           name: github-actions
#           known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'
#           config: |
#             host lsscse.com
#               IdentityFile ~/.ssh/github-actions
#               IdentitiesOnly yes
#               ForwardAgent yes

#       - name: Adding Known Hosts
#         run: ssh-keyscan -H ${{ secrets.SSH_HOST }}

#       - uses: actions/checkout@v2
#       - name: Set up Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: ['3.2.2']
#           bundler-cache: true # runs 'bundle install' and caches installed gems automatically

#       - name: Deploy to production
#         run: |
#           eval "$(ssh-agent -s)"
#           ssh-add ~/.ssh/github-actions
#           bundle exec cap production deploy